import { useEffect } from "react";
import Head from "next/head";

import Nav from "../components/Nav";

import "../styles/globals.css";

// import "../styles/tailwind.build.css";
import "../styles/bs.build.css";

import "../styles/styles.scss";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    typeof document !== undefined ? require("bootstrap") : null;
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
