// https://vercel-next-app-cdkk74h22-w5lev1f5y2m.vercel.app/

import { useEffect } from "react";
import Head from "next/head";

import Nav from "../components/Nav";

import "../styles/globals.css";
// import "../styles/tailwind.build.css";
import "../styles/bs.build.css";
import "../styles/styles.scss";

import AppContextProvider from "../components/store/app";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    typeof document !== undefined ? require("bootstrap") : null;
  }, []);
  return (
    <AppContextProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Component {...pageProps} />
    </AppContextProvider>
  );
}

export default MyApp;
